using API.Data;
using API.Middleware;
using Microsoft.EntityFrameworkCore;

var  MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

var builder = WebApplication.CreateBuilder(args);

// Add services to the container: We can inject them into other classes 
builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
// Registers StoreContext with dependency injection container
// Configures database provider to use SQLite
// Sets connection string from appsettings.json ("DefaultConnection")
// Makes StoreContext available for injection in controllers/services
builder.Services.AddDbContext<StoreContext>(opt =>
{
    opt.UseSqlite(builder.Configuration.GetConnectionString("DefaultConnection"));
});

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
        policy =>
        {
            // Allow this origin: React App Client to access the API
            policy.WithOrigins("https://localhost:3000")
                  .AllowCredentials() // ✅  Enable credentials (cookies)
                  .AllowAnyMethod()   // ✅  Allow all HTTP methods
                  .AllowAnyHeader();  // ✅ Allow all headers
        });
});

// This middleware is registered as a transient service in the DI container
// because it implement the 'IMiddleware' interface and has constructor 
// dependencies. The transient lifetime ensures that a fresh instance of the
// middleware is created for each HTTP request for purely stateless operations.
builder.Services.AddTransient<ExceptionMiddleware>();

var app = builder.Build();

// Middleware: Configure the HTTP request pipeline.

// Usage in the pipeline - positioned first
app.UseMiddleware<ExceptionMiddleware>(); 

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    // enables the Swagger middleware for serving the generated JSON 
    // document using the Swagger UI. Swagger is only enabled in a 
    // development environment.
    app.UseSwaggerUi(options =>
    {
        // The app uses the OpenAPI document generated by OpenApi, 
        // located at /openapi/v1.json, to generate the UI.
        options.DocumentPath = "/openapi/v1.json";
    });
}

app.UseCors(MyAllowSpecificOrigins);

app.MapControllers();

// Seeding Data to the Database
DbInitializer.InitDb(app);

app.Run();
